plugins {
    id 'com.cleanroommc.versioning'
    id 'java-library'
    id 'maven-publish'
}

group = providers.gradleProperty('group').get()
base.archivesName = 'versioning'

java {
    toolchain.languageVersion = JavaLanguageVersion.of(21)
    withSourcesJar()
    withJavadocJar()
}

tasks.named('compileJava', JavaCompile) {
    options.release = 8
    options.compilerArgs.add('-Xlint:-options')
}

repositories {
    mavenCentral()
}

dependencies {
    testImplementation platform('org.junit:junit-bom:5.11.4')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

tasks.named('test', Test) {
    useJUnitPlatform()
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}

publishing {
    publications {
        maven(MavenPublication) {
            artifactId = 'versioning'
            from components.java
        }
    }
    repositories {
        maven {
            name = 'CleanroomMaven'
            url = 'https://maven.cleanroommc.com'
            credentials(PasswordCredentials)
            authentication {
                basic(BasicAuthentication)
            }
        }
    }
}
